config/routes.rb
Rails.application.routes.draw do

  resources :system_settings
  resources :teams
  resources :team_efforts
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  match 'login', :to => 'sessions#new', :via => [:get, :post]
  match 'logout', :to => 'sessions#destroy', :via => [:get, :post]

  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/system_setting.rb
class SystemSetting < ApplicationRecord
end

app/controllers/system_settings_controller.rb
class SystemSettingsController < ApplicationController
  before_action :set_system_setting, only: %i[ show edit update destroy ]

  # GET /system_settings or /system_settings.json
  def index
    @system_settings = SystemSetting.all
  end

  # GET /system_settings/1 or /system_settings/1.json
  def show
  end

  # GET /system_settings/new
  def new
    @system_setting = SystemSetting.new
  end

  # GET /system_settings/1/edit
  def edit
  end

  # POST /system_settings or /system_settings.json
  def create
    @system_setting = SystemSetting.new(system_setting_params)

    respond_to do |format|
      if @system_setting.save
        format.html { redirect_to @system_setting, notice: "System setting was successfully created." }
        format.json { render :show, status: :created, location: @system_setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @system_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_settings/1 or /system_settings/1.json
  def update
    respond_to do |format|
      if @system_setting.update(system_setting_params)
        format.html { redirect_to @system_setting, notice: "System setting was successfully updated." }
        format.json { render :show, status: :ok, location: @system_setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @system_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_settings/1 or /system_settings/1.json
  def destroy
    @system_setting.destroy
    respond_to do |format|
      format.html { redirect_to system_settings_url, notice: "System setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_setting
      @system_setting = SystemSetting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def system_setting_params
      params.require(:system_setting).permit(:key, :value)
    end
end

app/helpers/system_settings_helper.rb
module SystemSettingsHelper
end

app/views/system_settings/_form.html.erb
<%= form_with(model: system_setting, local: true) do |form| %>
  <% if system_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(system_setting.errors.count, "error") %> prohibited this system_setting from being saved:</h2>

      <ul>
        <% system_setting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :key, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %><br/>
        <%= form.text_field :key, :class => 'form-control', :placeholder => ' Key ', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :value, :class => 'label-tag-style', :style => "text-transform: capitalize;color:black" %><br/>
        <%= form.text_field :value, :class => 'form-control', :placeholder => ' Value ', :required => true %>
      </div>
      <div class="actions">
        <%= form.submit(:class => 'btn btn-success btn-md') %>
      </div>
    </div>
  </div>
<% end %>

app/views/system_settings/edit.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('Edit System Setting') %></div>
    <div class="col-sm-6 text-right"><%= link_to 'Back', system_settings_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>
  <%= render 'form', system_setting: @system_setting %>
</div>

app/views/system_settings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('System Settings') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New System Setting', new_system_setting_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<table class="table table-bordered">
<tr class="tr_style">
      <th>Key</th>
      <th>Value</th>
      <th colspan="2"></th>
    </tr>
  </thead>
    <% @system_settings.each do |system_setting| %>
      <tr>
        <td><%= system_setting.key %></td>
        <td><%= system_setting.value %></td>
        <td><%= link_to 'Edit', edit_system_setting_path(system_setting) %></td>
        <td><%= link_to 'Destroy', system_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/system_settings/new.html.erb
<div style="padding: 5px">
  <div class="row">
    <div class="col-sm-6"><%= get_index_text('New System Setting') %></div>
    <div class="col-sm-6 text-right"><%= link_to 'Back', system_settings_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#99cc00 !important' %></div>
  </div>
  <%= render 'form', system_setting: @system_setting %>
</div>

app/views/system_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @system_setting.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @system_setting.value %>
</p>

<%= link_to 'Edit', edit_system_setting_path(@system_setting) %> |
<%= link_to 'Back', system_settings_path %>