config/routes.rb
Rails.application.routes.draw do

  resources :system_settings
  resources :teams
  resources :team_efforts
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  match 'login', :to => 'sessions#new', :via => [:get, :post]
  match 'logout', :to => 'sessions#destroy', :via => [:get, :post]

  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/team_effort.rb
class TeamEffort < ApplicationRecord
end

app/controllers/team_efforts_controller.rb
class TeamEffortsController < ApplicationController
  before_action :set_team_effort, only: %i[ show edit update destroy ]
  include ApplicationHelper
  # GET /team_efforts or /team_efforts.json
  def index
    @team_efforts = TeamEffort.all
  end

  # GET /team_efforts/1 or /team_efforts/1.json
  def show
  end

  # GET /team_efforts/new
  def new
    @team_effort = TeamEffort.new
    current_time = Time.now.utc.in_time_zone('Kolkata')
    @team_effort.log_date = params[:date].blank? ? current_time.to_date : Date.parse(params[:date])
    time_slots.each_with_index do |time_slot, index|
      if !time_slot.eql?("IN") && !time_slot.eql?("OUT") && !time_slot.eql?("Train-T")
        time_intervals = time_slot.split(' - ')
        start_time = DateTime.parse(time_intervals[0]+':00', current_time.to_date)
        end_time = DateTime.parse(time_intervals[1]+':00', current_time.to_date)
        formatted_time = DateTime.parse(current_time.strftime("%H:%M"), current_time.to_date)
        if formatted_time>=start_time-15.minutes && formatted_time<end_time+15.minutes
          @team_effort.time_slot=get_recent_time_slot(time_slot, index, time_slots)
          break
        end
      end
    end
  end

  # GET /team_efforts/1/edit
  def edit
  end

  # POST /team_efforts or /team_efforts.json
  def create
    @team_effort = TeamEffort.new(team_effort_params)
    @team_effort.user_id=current_user.id
    @team_effort.name=current_user.name
    if params[:team_effort][:time_slot].eql?('OUT')
      @team_effort.errors[:jira_id] = 'Please enter LOW or MEDIUM or HIGH.' if !params[:team_effort][:jira_id].eql?('LOW') && !params[:team_effort][:jira_id].eql?('MEDIUM') && !params[:team_effort][:jira_id].eql?('HIGH')
    end
    respond_to do |format|
      if ((@team_effort.errors.blank? && @team_effort.save))
        format.html { redirect_to "/team_efforts/new#new_effort", notice: '' }
      else
        format.html { render action: "new" }
      end
    end
  end


  def create1
    @team_effort = TeamEffort.new(params[:team_effort])
    @team_effort.user_id=current_user.id
    @team_effort.name=current_user.display_name
    if params[:team_effort][:time_slot].eql?('Train-T')
      @team_effort.errors[:jira_id] = 'Please enter decimal Value .' if params[:team_effort][:jira_id].to_d<= 0.0
    elsif params[:team_effort][:time_slot].eql?('OUT')
      @team_effort.errors[:jira_id] = 'Please enter LOW or MEDIUM or HIGH.' if !params[:team_effort][:jira_id].eql?('LOW') && !params[:team_effort][:jira_id].eql?('MEDIUM') && !params[:team_effort][:jira_id].eql?('HIGH')
    end
    puts @team_effort.errors
    respond_to do |format|
      if ((@team_effort.errors.blank? && @team_effort.save))
        format.html { redirect_to "/team_efforts/new#new_effort", notice: '' }
        format.json { render json: @team_effort, status: :created, location: @team_effort }
      else
        format.html { render action: "new" }
        format.json { render json: @team_effort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_efforts/1 or /team_efforts/1.json
  def update
    respond_to do |format|
      if @team_effort.update(team_effort_params)
        format.html { redirect_to @team_effort, notice: "Team effort was successfully updated." }
        format.json { render :show, status: :ok, location: @team_effort }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team_effort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_efforts/1 or /team_efforts/1.json
  def destroy
    @team_effort.destroy
    respond_to do |format|
      format.html { redirect_to team_efforts_url, notice: "Team effort was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  def get_recent_time_slot(time_slot, index, time_slots)
    result=''
    if !TeamEffort.find_by_time_slot_and_user_id_and_log_date(time_slot, current_user.id, Time.now.utc.in_time_zone('Kolkata').to_date).blank?
      result=get_recent_time_slot(time_slots[index+1], index+1, time_slots) if index+1<time_slots.size
    else
      result=time_slot
    end
    result
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_effort
      @team_effort = TeamEffort.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_effort_params
      params.require(:team_effort).permit(:name, :user_id, :jira_id, :description, :log_date, :time_slot, :comment)
    end
end

app/helpers/team_efforts_helper.rb
module TeamEffortsHelper
end

app/views/team_efforts/_form.html.erb
<%= form_with(model: team_effort, local: true) do |form| %>
  <% if team_effort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_effort.errors.count, "error") %> prohibited this team_effort from being saved:</h2>

      <ul>
        <% team_effort.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12 padding-left-0">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.text_field(:log_date, :placeholder => ' Date', :class => 'datepicker form-control') %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= form.select :time_slot, options_for_select(time_slots, @team_effort.time_slot), {:prompt=>'Select Time Slot'}, {:class => 'form-control select_tag_style'} %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">

          <%= form.text_field :jira_id, :placeholder => 'Jira Id', :class => 'form-control' %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= form.text_area :description, :placeholder => 'Notes', :size => "100x2", :class => 'form-control' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12 text-right">
    <div class="actions">
      <%= form.submit "Team Effort >> #{current_user.name}" , :class => "zl_round_button2 profile_submit" %>
    </div>
  </div>
<% end %>

app/views/team_efforts/edit.html.erb
<h1>Editing Team Effort</h1>

<%= render 'form', team_effort: @team_effort %>

<%= link_to 'Show', @team_effort %> |
<%= link_to 'Back', team_efforts_path %>

app/views/team_efforts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Efforts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Jira</th>
      <th>Description</th>
      <th>Log date</th>
      <th>Time slot</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_efforts.each do |team_effort| %>
      <tr>
        <td><%= team_effort.name %></td>
        <td><%= team_effort.user_id %></td>
        <td><%= team_effort.jira_id %></td>
        <td><%= team_effort.description %></td>
        <td><%= team_effort.log_date %></td>
        <td><%= team_effort.time_slot %></td>
        <td><%= team_effort.comment %></td>
        <td><%= link_to 'Show', team_effort %></td>
        <td><%= link_to 'Edit', edit_team_effort_path(team_effort) %></td>
        <td><%= link_to 'Destroy', team_effort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Effort', new_team_effort_path %>

app/views/team_efforts/new.html.erb
<div><h3>Team Effort &nbsp;&nbsp;&nbsp;<span style="color: blue"><%= current_user.name %></span></h3></div>
<% @team_efforts = TeamEffort.where('user_id = ?', current_user.id).limit(18).order('updated_at DESC') %>

<div class="row" style="width: 100%;position: relative;margin-right: 0px">
  <% @team_efforts.each do |team_effort| %>

    <% if team_effort.time_slot.eql?("IN") || team_effort.time_slot.eql?("OUT")
         status = team_effort.created_at.strftime('%H : %M')
       else
         status = team_effort.jira_id
       end
    %>

    <div class="col-sm-4">
      <div class="each_team_effort_div_style">
        <div class="col-sm-12 each_team_effort_row_style" style="background-color: #99CC00;padding-left: 0px;padding-right: 0px;max-height:40px;">
          <div class="col-sm-7 each_team_effort_field_style"><%= team_effort.time_slot %></div>
          <div class="col-sm-5 each_team_effort_field_style" style="text-align: right"><%= team_effort.log_date %></div>
        </div>
        <div class="col-sm-12 each_team_effort_field_style" style="background-color: #99CC00;text-align: center;max-height:40px;"><%= status %></div>
        <div class=" col-sm-12 each_team_effort_field_style text-left" style="font-size: 14px ;font-weight: normal;padding-left: 5px;vertical-align: top;max-height: 70px;"><%= simple_format team_effort.description %></div>
        <% if !team_effort.comment.blank? %>
          <div class="col-sm-12 each_team_effort_row_style_comment" style="background-color:#33CCFF;vertical-align: bottom;max-height: 70px;"> <%= simple_format team_effort.comment %> </div>
        <% end %>
        <div class="col-sm-12 text-right" style="padding-left: 0px;position: absolute;bottom: 15px;right: 5px; ">
          <%#= link_to image_tag('add-icon.png', :width => "20px", :class => "icon_img_style"), "/team_efforts/add_comment?id=#{team_effort.id}" %>
        </div>
      </div>
    </div>

  <% end %>
  <div class="col-sm-12 text-right" style="padding: 10px;">
    <a href="/team_efforts/" target="_blank" class="zl_round_button2 profile_submit"> All Team Efforts</a>
  </div>
  <div class="col-sm-12 text-right" style="padding: 10px">
    <a href="/team-effort-summary" target="_blank" class="zl_round_button2 profile_submit">Team Effort Summary</a>
  </div>

</div>

<div style="padding-top: 25px;padding-bottom: 20px" id="new_effort">
  <%= render 'form', team_effort: @team_effort %>
</div>

app/views/team_efforts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @team_effort.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @team_effort.user_id %>
</p>

<p>
  <strong>Jira:</strong>
  <%= @team_effort.jira_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @team_effort.description %>
</p>

<p>
  <strong>Log date:</strong>
  <%= @team_effort.log_date %>
</p>

<p>
  <strong>Time slot:</strong>
  <%= @team_effort.time_slot %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @team_effort.comment %>
</p>

<%= link_to 'Edit', edit_team_effort_path(@team_effort) %> |
<%= link_to 'Back', team_efforts_path %>